Add py2bexp CLI tool to convert qlassf functions to boolean expressions
dakk/qlasskit pull request #56
Opened 2024-06-11 19:07 UTC by tomv42

**Summary:**

This pull request introduces the `py2bexp` command-line tool to the `qlasskit` package. The tool converts qlassf functions in a Python script to boolean expressions. It also includes initial tests for the functionality.

**Changes:**

1. **Added `py2bexp.py` to `qlasskit/tools` package:**
   - Implements the conversion of qlassf functions to boolean expressions.
   - Supports reading from a file or stdin.
   - Allows specifying entrypoint function, output file, expression form, and output format.
   - Includes command-line arguments parsing with `argparse`.

2. **Updated `setup.py`:**
   - Added `py2bexp` as a console script entry point for seamless installation and usage.

3. **Initial Tests in `test_tools.py`:**
   - Included tests for help and version commands.
   - Added tests for default behavior, specific entrypoint, and different expression forms.
   - Verified DIMACS format output for CNF.
   - **Note**: Tests currently do not have assertions but printing results looks good.
       - I don't know what kind of assertion would be appropriate...
   
**Related Issue:**

This PR resolves issue #28

@dakk, I'm looking forward to your feedback.

2024-06-11 19:16 UTC, dakk commented
Thank you, I will review tomorrow UTC; in the meanwhile, can you please take care of failing tests on CI?

2024-06-11 19:23 UTC, tomv42 commented
Yes, I'm working on it.

2024-06-11 22:50 UTC, tomv42 commented
I added satisfactory assertions to all the unit tests except one, by comparing the results against sympy expressions and testing that the form is the right one with sympy too.

This didn't work for anf where calling `is_anf` resulted in a type error. Which is weird because it didn't for the others.

For the DIMACS test, as the order of the symbols when converting to DIMACS is not guaranteed, and all the permutations of the names of the symbols give equivalent expressions, the test compares all the possible permutations of the 3 symbols.

2024-06-12 06:23 UTC, dakk requested changes
Excellent work, I propose you some minor changes and then I can merge it.

2024-06-12 06:23 UTC, dakk commented on test/test_tools.py
> +        expected1 = And(Or(x, y, Not(z)), Or(z, Not(y)))
here it is better to use itertools.permutations:

```python
from itertools import permutations

assert_val = False
for sl in permutations(symbols):
   exp = And(Or(sl[0], sl[2], Not(sl[1])), Or(sl[1], Not(sl[2])))
   assert_val = assert_val or expr.equals(exp)

self.assertTrue(assert_val)
```

something like this

2024-06-12 06:23 UTC, dakk commented on qlasskit/tools/py2bexp.py
> +def find_last_qlassf(qlassf_list):
move this function to tools.py

2024-06-12 06:23 UTC, dakk commented on test/test_tools.py
> +        print(result.stdout)
remove this and other prints from test

2024-06-12 07:17 UTC, dakk commented
@tomv42 with very few modification, you can also write the code for this: https://github.com/dakk/qlasskit/issues/26 , if you have time

2024-06-12 10:03 UTC, dakk approved these changes

2024-06-12 10:04 UTC, merged